### ISSUE TITLE
Test code need gt and the result is not good

### ISSUE THREAD

**Issue by YunanWu2168** [yiyulics/CSEC#5]
Hi, thank you for the great work! I have tried your model on my photo below and found the results are not that good.

At the same time, the test code would need the gt path or it has errors, so I just put the same test path here. Please let me know if I did anything incorrectly. Thank you so much!

Here is my input, which generated artifscts on the mountains and the lake. 
![photography-tips-norway-2](https://github.com/user-attachments/assets/8d960c27-aa7b-4328-9b26-16e8f7baebd0)

And here  is the output from the normal folder:
![photography-tips-norway](https://github.com/user-attachments/assets/43a66828-1b17-4d2e-a23f-bf0f38df60b0)

**Comment by yiyulics** [comment]
Hi @YunanWu2168,

During the inference phase, if there's no need to compute metrics for your test set, you may configure `test.GT` same as `test.input`. Alternatively, you can set `test.GT` to `none` if that suits your requirements better.

As discussed in the limitation section of the paper, CNN-based models often struggle with accurately predicting the original colors and details in large, fully saturated, or over-exposed areas due to the minimal information available in such regions.

Additionally, please note that the `normal` folder contains the pseudo-normal features we described in the paper. All final results will be stored as .png files in the `test_results` folder.

**Comment by yiyulics** [comment]
I am closing this issue. Feel free to reopen if you have any more questions.

**Comment by YunanWu2168** [comment]
Thank you for your answer!
I wonder if you have any suggestions on how to better solve this over-saturated issue? I have retrained the model on my own images but found this issue still existed in some of the cases. 

Thank you again.

**Comment by yiyulics** [comment]
Personally, it's understandable that neural networks may find it very difficult, or even impossible, to predict the original details given all (1, 1, 1)s around (i.e., fully saturated pixels). One potential solution is to employ a generative model to generate content in those saturated areas. Perhaps you could give that a try.
